### ISSUE TITLE
Is this how it should be counted?

### ISSUE THREAD

**Issue by simPod** [TomasVotruba/cognitive-complexity#1]
```php
function get_words_from_number(int $number): string
{
    if ($number === 1) {            // + 1
        return 'one';
    }

    if ($number === 2) {      // + 1
        return 'couple';
    }

    if ($number === 3) {      // + 1
        return 'a few';
    } else {                        // + 1
        $amountInWords = 'a lot';
    }

    return $amountInWords;
}
```

I always though the cognitive complexity is reduced by exiting early. But even though I take the function from https://tomasvotruba.com/blog/keep-cognitive-complexity-low-with-phpstan/ and add few early exit points, this extension still counts complexity as 4.

When I transform it into

```php
function get_words_from_number(int $number): string
{
    if ($number === 1) {            // + 1
        return 'one';
    }

    if ($number === 2) {      // + 1
        return 'couple';
    }

    if ($number === 3) {      // + 1
        return 'a few';
    }

    return 'a lot';
}
```

I achieve complexity 3.

Is it correct behaviour?

**Comment by TomasVotruba** [comment]
That is correct. The if/else can be changed to if/early return, which is easier to read.

See https://www.sonarsource.com/resources/cognitive-complexity/ for axiom methodology of this metric.
