### ISSUE TITLE
Support for T_MATCH

### ISSUE THREAD

**Issue by epic-64** [TomasVotruba/cognitive-complexity#7]
Hi there, I didn't find anything T_MATCH related in the src or tests.

Could you please add T_MATCH with the same rules as T_SWITCH?

Namely, opening a `match` should add 1 complexity (on top of any existing nesting level), and should also increment the nesting level.

Example function for reference:
```php
function matchIncrementsNesting($number) {
    $a = true;
    $b = true;

    if ($a) { // +1 opening if, increment nesting
        match ($number) { // +1 opening match, +1 from nesting, increment nesting
            1       => $b ? "one" : "uno", // +1 using ternary, +2 from nesting
            2       => "a couple",
            3       => "a few",
            default => "lots",
        };
    }
}

// Cognitive Complexity 6
```

**Comment by TomasVotruba** [comment]
Hi, feel free to send a PR to improve these rules. I only accept PRs here for lack of time.
Thanks for understanding :+1:
