### ISSUE TITLE
Enhance phpstan configuration with specific file exclusions for cognitive complexity

### ISSUE THREAD

**Issue by MassimoDeSabbata** [TomasVotruba/cognitive-complexity#8]
# Issue

I'm currently using phpstan with the following configuration:

```xml
 parameters:
      ignoreErrors:
          - identifier: 
              missingType.generics
      level: 6
      paths:
          - src/
      excludePaths:
          - some/path/to/exclude/from/phpstan
      cognitive_complexity:
          class: 50
          function: 8
```

While the *excludePaths* option allows excluding entire directories from phpstan analysis, I have specific files that I'd like to include in the analysis but exclude from the cognitive complexity check.

# Request
Would it be possible to implement an additional *excludePaths* option specifically for the *cognitive_complexity* section within the library configuration? This would allow for more granular control over the analysis.

## Example

```xml
 parameters:
      ignoreErrors:
          - identifier: 
              missingType.generics
      level: 6
      paths:
          - src/
      excludePaths:
          - some/path/to/exclude/from/phpstan
      cognitive_complexity:
          class: 50
          function: 8
          excludePaths:
                    - some/path/to/exclude/from/cognitive/complexity
```

**Comment by TomasVotruba** [comment]
Hi, thanks for proposal.
 You can already exclude any rule by message in specific paths natively in PHPStan. 

https://phpstan.org/user-guide/ignoring-errors#ignoring-in-configuration-file
